#    This config file is for the EEND-EDA adaptation stage (training on flexible number of speakers).
#    For the details about EEND-EDA, refer to the following papers:
#    EEND-EDA: https://arxiv.org/pdf/2005.09921.pdf, https://arxiv.org/pdf/2106.10654.pdf

# network architecture
# encoder related
encoder: transformer
encoder_conf:
    input_layer: "conv2d"
    num_blocks: 4
    linear_units: 512
    dropout_rate: 0.1
    output_size: 256  # dimension of attention
    attention_heads: 4
    attention_dropout_rate: 0.1

label_aggregator: label_aggregator
label_aggregator_conf:
    win_length: 1024
    hop_length: 512  # This value should be set to:
                    # frontend hop_length * subsampling factor (corresponding to encoder input_layer)
                    # subsampling factors: 1 (linear), 2 (conv2d2), 4 (conv2d), 6 (conv2d6), 8 (conv2d8)
# attractor related
attractor: rnn
attractor_conf:
    unit: 256 # same as encoder output size
    layer: 1
    dropout: 0.0
    attractor_grad: True


# minibatch related
#batch_type: folded
batch_type: sorted
batch_size: 1

# optimization related
optim: adam
accum_grad: 16
grad_clip: 5
max_epoch: 50
optim_conf:
    lr: 0.0001

# others:
best_model_criterion:
-  - valid
   - acc
   - max
-  - train
   - acc
   - max
keep_nbest_models: 10

specaug: specaug
specaug_conf:
    apply_time_warp: false
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2